name: ChatUtils
version: 1.2.1
main: com.queazified.chatutils.ChatUtils
api-version: 1.20
author: Queazified
description: Simple chat utilities (e.g., share your held item in chat).
website: https://queazified.co.uk

commands:
  hand:
    description: Show the item in your hand to the chat
    usage: /hand
    permission: chatutils.hand
  iteminfo:
    description: Show detailed info about the item in your hand
    usage: /iteminfo
    permission: chatutils.iteminfo

permissions:
  chatutils.hand:
    description: Allows use of /hand
    default: true
  chatutils.iteminfo:
    description: Allows use of /iteminfo
    default: op
